### ISSUE TITLE
esxi support ESXi-8.0.0-20513097

### ISSUE THREAD

**Issue by ashleyw-gh** [DrDonk/esxi-unlocker#12] opened 2022-11-04 10:42 UTC
Hi, I added some detail to #10 but the issue was already closed.
Please can the functionality of unlocker be checked with esxi8 as I'm getting some errors as described in #10 
 ```
PatchVMKCTL 4.0.3
=================
(c) 2014-2022 David Parsons

Filename: ./tmp/lib64/libvmkctl.so
Traceback (most recent call last):
  File "./patchvmkctl", line 96, in <module>
    main()
  File "./patchvmkctl", line 81, in main
    f(filename)
  File "./patchvmkctl", line 41, in patchvmkctl
    f.seek(applesmc)
OSError: [Errno 22] Invalid argument
```

here is what the check returns;
```
[root@localhost:/vmfs/volumes/5d72331d-3715a90a-1f62-40b076d8cbfa/media/esxi-unlocker-4.0.3] ./check
VMware ESXi Unlocker 4.0.3
==========================
(c) 2011-2022 David Parsons

Checking unlocker...
Current version of ESXi: VMware ESXi 8.0.0 build-20513097
Patch built for ESXi: VMware ESXi 8.0.0 build-20513097
Checking VMTAR loaded...
apple.v00 loaded
Checking vmx vSMC status...
/bin/vmx
/bin/vmx-debug
/bin/vmx-stats
vmx patched
Checking smcPresent status...
smcPresent = true
```

just as part of my testing. I took the approach of build a Ventura VM in VMware workstation using a vmdk and was able to boot this fine after installing the PC version of unlocker. I think ran the conversion on the disk to type 4, and then rechecked the VM was booting correctly on workstation. All was fine at this stage. (this is on an Intel machine)
I took a binary copy of the VM folder tree and uploaded it via scp to the esxi host and then registered it, after adding in the CPU mask for ESXi.
It then gets stuck in the same boot look as a fresh ISO as described above.
So my conclusion is that the PC version is patching VMware workstation in such a way where Ventua will boot, but the esxi unlocker is not patching the esxi host correctly (atleast in the case of esxi8 that I have access to).

looking at the esxi logs during the reboot cycle it appears this is what triggers it;
```
022-11-05T04:43:25.209Z Wa(03) vcpu-3 - DarwinPanic: panic(cpu 3 caller 0xffffff8010e45885):  initproc failed to start -- exit reason namespace 6 subcode 0x1 description: Library not loaded: /usr/lib/libSystem.B.dylib
2022-11-05T04:43:25.211Z In(05) vcpu-3 - Chipset: The guest has requested that the virtual machine be hard reset.
```
but this seems to be the same issue that others are struggling with on esxi right now....

thanks!

**Comment by DrDonk** [comment] 2022-11-05 12:01
Looks like I closed the wrong issue. Sorry about that. Ventura running on Workstation is still hit and miss and nnot sure what causes it to fail. In additon don't expect VMware to add support for anything after Monterey as they have dropped macOS guest support.

FYI The patches are exactly the same just written in Python for ESXi and Go for Windows/Linux. I test to make sure that the binaries are correctly patched with additional tools I have (in the unlocker repo) against a set of samples from all VMware products. So I don't believe that is the cause.

So let's get the ESXi system into a know state. Can you login via SSH or Console and capture the following command output please? Attach output to the issue in a file.

1. esxcli system visorfs tardisk list
2. ls -la /bootbank
3. ls -la /altbootbank

And the CPUs you are using are AMD on ESXi with Intel on Workstation.

So also attach VMX and vmware.log files from ESXi and Workstation please.

**Comment by ashleyw-gh** [comment] 2022-11-06 22:36
thanks,
The CPU on VMware Workstation which is working fine is an Intel i7-4770 CPU.
The CPU on esxi8 is an AMD 5950x.
I've atatched the vmx and log files form VMware workstation and from esxi.
I'm happy to share my VM image (its 40GB) (it was built on workstation on Venture beta media, then upgraded to the final release, and then disk was coverted to type 4 and the VM was binary transferred to my esxi8 host and the virtual hw upgraded to level 20 to allow the VM to be edited). (7zip size of the image is still 30GB).
With all the noise around AVX/AVX2/AVX-512, my guess is that there are there are differences in the way these are handled by the AMD CPU compared to Intel (but this is just a hunch).
I do have limited access to a Xeon 4214R and I did try earlier this morning but this broke the EVC settings on the esxi host so I had to roll back the unlocker as the server is used as an out of bands management host for our main clusters. 

I did have a play at masking the AVX/AVX2 flags in the CPUID, but this did not fix the issue as per, but this made no difference;
https://communities.vmware.com/t5/VMware-Workstation-Pro/Disable-AVX-instruction-support-in-VM/td-p/2928712

Any reason you can think of why the unlocker gives the following error on the PathVMKCTL stage - or is this only relevant to vCentre managed hosts (which this is not)?
```
PatchVMKCTL 4.0.3
=================
(c) 2014-2022 David Parsons

Filename: ./tmp/lib64/libvmkctl.so
Traceback (most recent call last):
  File "./patchvmkctl", line 96, in <module>
    main()
  File "./patchvmkctl", line 81, in main
    f(filename)
  File "./patchvmkctl", line 41, in patchvmkctl
    f.seek(applesmc)
OSError: [Errno 22] Invalid argument
```
My old Catalina macOS continues to boot without an issue on esxi8.
Any thoughts?

1. esxcli system visorfs tardisk list
```
[root@localhost:~] esxcli system visorfs tardisk list
Tardisk Name  System         Size
------------  ------  -----------
vmx.v00         true  139892704 B
vim.v00         true  192964848 B
tpm.v00         true      24430 B
sb.v00          true  239677996 B
s.v00           true  158149072 B
atlantic.v00    true    1446953 B
bcm_mpi3.v00    true     275341 B
bnxtnet.v00     true    1028799 B
bnxtroce.v00    true     421958 B
brcmfcoe.v00    true    2314802 B
cndi_igc.v00    true     140303 B
dwi2c.v00       true      78009 B
elxiscsi.v00    true     606402 B
elxnet.v00      true     669915 B
i40en.v00       true     853331 B
iavmd.v00       true     778777 B
icen.v00        true    2577969 B
igbn.v00        true     339836 B
ionic_en.v00    true     516419 B
irdman.v00      true     608616 B
iser.v00        true     282682 B
ixgben.v00      true     554849 B
lpfc.v00        true    3277043 B
lpnic.v00       true     667709 B
lsi_mr3.v00     true     382527 B
lsi_msgp.v00    true     504998 B
lsi_msgp.v01    true     697407 B
lsi_msgp.v02    true     550605 B
mtip32xx.v00    true     258407 B
ne1000.v00      true     677917 B
nenic.v00       true     279057 B
nfnic.v00       true     806973 B
nhpsa.v00       true     727347 B
nmlx5_co.v00    true    3846791 B
nmlx5_rd.v00    true     360768 B
ntg3.v00        true     123428 B
nvme_pci.v00    true     147649 B
nvmerdma.v00    true     184387 B
nvmetcp.v00     true     233537 B
nvmxnet3.v00    true     200772 B
nvmxnet3.v01    true     172096 B
pvscsi.v00      true     118846 B
qcnic.v00       true     307325 B
qedentv.v00     true    4211391 B
qedrntv.v00     true    3461185 B
qfle3.v00       true    3191961 B
qfle3f.v00      true    1400959 B
qfle3i.v00      true     376896 B
qflge.v00       true     512743 B
rdmahl.v00      true     720958 B
rste.v00        true     848298 B
sfvmk.v00       true     934445 B
smartpqi.v00    true     715431 B
vmkata.v00      true     212532 B
vmksdhci.v00    true     327874 B
vmkusb.v00      true    1135528 B
vmw_ahci.v00    true     243221 B
bmcal.v00       true      74184 B
clusters.v00    true   38470365 B
crx.v00         true   45582416 B
drivervm.v00    true  109580491 B
elx_esx_.v00    true    2385008 B
btldr.v00       true    1494414 B
esx_dvfi.v00    true     541173 B
esx_ui.v00      true   25319141 B
esxupdt.v00     true    2683251 B
tpmesxup.v00    true       9123 B
weaselin.v00    true    2851896 B
esxio_co.v00    true     645936 B
loadesx.v00     true    4492060 B
lsuv2_hp.v00    true      72512 B
lsuv2_in.v00    true      77512 B
lsuv2_ls.v00    true    1177840 B
lsuv2_nv.v00    true      14248 B
lsuv2_oe.v00    true      14256 B
lsuv2_oe.v01    true      14248 B
lsuv2_sm.v00    true      55568 B
native_m.v00    true    2474569 B
qlnative.v00    true    2854433 B
trx.v00         true   22844763 B
vdfs.v00        true   14202650 B
vmware_e.v00    true     228536 B
vsan.v00        true   53074168 B
vsanheal.v00    true    8856099 B
vsanmgmt.v00    true   28934744 B
xorg.v00        true    3514869 B
gc.v00          true      69056 B
imgdb.tgz       true    2314240 B
basemisc.tgz    true   30648320 B
state.tgz       true     240128 B
apple.v00       true  107162336 B
```

2. ls -la /bootbank
3. ls -la /altbootbank

```
[root@localhost:~] ls -la /bootbank
lrwxrwxrwx    1 root     root            49 Nov  6 21:38 /bootbank -> /vmfs/volumes/052b1156-484f41d5-29a6-52a539b81065
[root@localhost:~] ls -la /altbootbank
lrwxrwxrwx    1 root     root            49 Nov  6 21:38 /altbootbank -> /vmfs/volumes/6c42042f-664bfdc0-37a4-4cc122bb76ad
```

because the /bootbank and /altbootbank are mounts, I've listed the contents of the directories below;

```
[root@localhost:~] ls -al /vmfs/volumes/052b1156-484f41d5-29a6-52a539b81065
total 326880
drwxr-xr-x    1 root     root             8 Jan  1  1970 .
drwxr-xr-x    1 root     root           512 Nov  6 21:58 ..
-rwx------    1 root     root      37841088 Nov  6 21:37 apple.v00
-rwx------    1 root     root        250528 Oct 12 20:44 atlantic.v00
-rwx------    1 root     root        147797 Oct 12 20:44 b.b00
-rwx------    1 root     root       2767467 Oct 12 20:44 basemisc.tgz
-rwx------    1 root     root         77283 Oct 12 20:44 bcm_mpi3.v00
-rwx------    1 root     root         29555 Oct 12 20:44 bmcal.v00
-rwx------    1 root     root        283883 Oct 12 20:44 bnxtnet.v00
-rwx------    1 root     root        116359 Oct 12 20:44 bnxtroce.v00
-rwx------    1 root     root          1650 Nov  6 21:37 boot.cfg
-rwx------    1 root     root        601530 Oct 12 20:44 brcmfcoe.v00
-rwx------    1 root     root       1152352 Oct 12 20:44 btldr.v00
-rwx------    1 root     root      13234574 Oct 12 20:44 clusters.v00
-rwx------    1 root     root         45484 Oct 12 20:44 cndi_igc.v00
-rwx------    1 root     root      17976400 Oct 12 20:44 crx.v00
-rwx------    1 root     root      38810988 Oct 12 20:44 drivervm.v00
-rwx------    1 root     root         16607 Oct 12 20:44 dwi2c.v00
-rwx------    1 root     root        459848 Oct 12 20:44 elx_esx_.v00
-rwx------    1 root     root        156775 Oct 12 20:44 elxiscsi.v00
-rwx------    1 root     root        178688 Oct 12 20:44 elxnet.v00
-rwx------    1 root     root        117038 Oct 12 20:44 esx_dvfi.v00
-rwx------    1 root     root       4885184 Oct 12 20:44 esx_ui.v00
-rwx------    1 root     root        193200 Oct 12 20:44 esxio_co.v00
-rwx------    1 root     root        569248 Oct 12 20:44 esxupdt.v00
-rwx------    1 root     root            20 Oct 12 20:44 features.gz
-rwx------    1 root     root         16194 Oct 12 20:44 gc.v00
-rwx------    1 root     root        256815 Oct 12 20:44 i40en.v00
-rwx------    1 root     root        219072 Oct 12 20:44 iavmd.v00
-rwx------    1 root     root        552541 Oct 12 20:44 icen.v00
-rwx------    1 root     root         99476 Oct 12 20:44 igbn.v00
-rwx------    1 root     root        282817 Oct 12 20:44 imgdb.tgz
-rwx------    1 root     root        136185 Oct 12 20:44 ionic_en.v00
-rwx------    1 root     root        205542 Oct 12 20:44 irdman.v00
-rwx------    1 root     root         79994 Oct 12 20:44 iser.v00
-rwx------    1 root     root        164803 Oct 12 20:44 ixgben.v00
-rwx------    1 root     root           118 Nov  6 21:38 jumpstrt.gz
-rwx------    1 root     root       6153968 Oct 12 20:44 k.b00
-rwx------    1 root     root       1164727 Oct 12 20:44 loadesx.v00
-rwx------    1 root     root        855096 Oct 12 20:44 lpfc.v00
-rwx------    1 root     root        177960 Oct 12 20:44 lpnic.v00
-rwx------    1 root     root        100882 Oct 12 20:44 lsi_mr3.v00
-rwx------    1 root     root        136875 Oct 12 20:44 lsi_msgp.v00
-rwx------    1 root     root        188408 Oct 12 20:44 lsi_msgp.v01
-rwx------    1 root     root        148782 Oct 12 20:44 lsi_msgp.v02
-rwx------    1 root     root         24678 Oct 12 20:44 lsuv2_hp.v00
-rwx------    1 root     root         25353 Oct 12 20:44 lsuv2_in.v00
-rwx------    1 root     root        437031 Oct 12 20:44 lsuv2_ls.v00
-rwx------    1 root     root          2792 Oct 12 20:44 lsuv2_nv.v00
-rwx------    1 root     root          4415 Oct 12 20:44 lsuv2_oe.v00
-rwx------    1 root     root          4160 Oct 12 20:44 lsuv2_oe.v01
-rwx------    1 root     root         22170 Oct 12 20:44 lsuv2_sm.v00
-rwx------    1 root     root         72241 Oct 12 20:44 mtip32xx.v00
-rwx------    1 root     root        617410 Oct 12 20:44 native_m.v00
-rwx------    1 root     root        178931 Oct 12 20:44 ne1000.v00
-rwx------    1 root     root         78051 Oct 12 20:44 nenic.v00
-rwx------    1 root     root        219710 Oct 12 20:44 nfnic.v00
-rwx------    1 root     root        189783 Oct 12 20:44 nhpsa.v00
-rwx------    1 root     root        980782 Oct 12 20:44 nmlx5_co.v00
-rwx------    1 root     root        112448 Oct 12 20:44 nmlx5_rd.v00
-rwx------    1 root     root         35727 Oct 12 20:44 ntg3.v00
-rwx------    1 root     root         39892 Oct 12 20:44 nvme_pci.v00
-rwx------    1 root     root         48770 Oct 12 20:44 nvmerdma.v00
-rwx------    1 root     root         61621 Oct 12 20:44 nvmetcp.v00
-rwx------    1 root     root         58527 Oct 12 20:44 nvmxnet3.v00
-rwx------    1 root     root         49427 Oct 12 20:44 nvmxnet3.v01
-rwx------    1 root     root        226070 Oct 12 20:45 preupgrade-state.tgz
-rwx------    1 root     root          9093 Oct 12 20:44 procfs.b00
-rwx------    1 root     root         30031 Oct 12 20:44 pvscsi.v00
-rwx------    1 root     root         89888 Oct 12 20:44 qcnic.v00
-rwx------    1 root     root       1423121 Oct 12 20:44 qedentv.v00
-rwx------    1 root     root       1222720 Oct 12 20:44 qedrntv.v00
-rwx------    1 root     root        947178 Oct 12 20:44 qfle3.v00
-rwx------    1 root     root        344829 Oct 12 20:44 qfle3f.v00
-rwx------    1 root     root        110024 Oct 12 20:44 qfle3i.v00
-rwx------    1 root     root        202056 Oct 12 20:44 qflge.v00
-rwx------    1 root     root        814471 Oct 12 20:44 qlnative.v00
-rwx------    1 root     root        165066 Oct 12 20:44 rdmahl.v00
-rwx------    1 root     root        218362 Oct 12 20:44 rste.v00
-rwx------    1 root     root      24954657 Oct 12 20:44 s.v00
-rwx------    1 root     root      54454237 Oct 12 20:44 sb.v00
-rwx------    1 root     root        246318 Oct 12 20:44 sfvmk.v00
-rwx------    1 root     root        176928 Oct 12 20:44 smartpqi.v00
-rwx------    1 root     root        230165 Nov  6 21:44 state.tgz
-rwx------    1 root     root          9204 Oct 12 20:44 tpm.v00
-rwx------    1 root     root          3591 Oct 12 20:44 tpmesxup.v00
-rwx------    1 root     root      10502636 Oct 12 20:44 trx.v00
-rwx------    1 root     root         15291 Oct 12 20:44 uc_amd.b00
-rwx------    1 root     root            29 Oct 12 20:44 uc_hygon.b00
-rwx------    1 root     root       1941978 Oct 12 20:44 uc_intel.b00
-rwx------    1 root     root            57 Nov  2 01:07 useropts.gz
-rwx------    1 root     root       5216593 Oct 12 20:44 vdfs.v00
-rwx------    1 root     root      31236118 Oct 12 20:44 vim.v00
-rwx------    1 root     root         57799 Oct 12 20:44 vmkata.v00
-rwx------    1 root     root         91147 Oct 12 20:44 vmksdhci.v00
-rwx------    1 root     root        335609 Oct 12 20:44 vmkusb.v00
-rwx------    1 root     root         66467 Oct 12 20:44 vmw_ahci.v00
-rwx------    1 root     root         55230 Oct 12 20:44 vmware_e.v00
-rwx------    1 root     root      39965984 Oct 12 20:44 vmx.v00
-rwx------    1 root     root      16219038 Oct 12 20:44 vsan.v00
-rwx------    1 root     root        532603 Oct 12 20:44 vsanheal.v00
-rwx------    1 root     root       5523961 Oct 12 20:44 vsanmgmt.v00
-rwx------    1 root     root       1230728 Oct 12 20:44 weaselin.v00
-rwx------    1 root     root       1450533 Oct 12 20:44 xorg.v00
[root@localhost:~] ls -la /vmfs/volumes/6c42042f-664bfdc0-37a4-4cc122bb76ad
total 289960
drwxr-xr-x    1 root     root             8 Jan  1  1970 .
drwxr-xr-x    1 root     root           512 Nov  6 21:59 ..
-rwx------    1 root     root        250550 Oct  7 22:50 atlantic.v00
-rwx------    1 root     root        147797 Oct  7 22:50 b.b00
-rwx------    1 root     root       2797900 Oct  7 22:50 basemisc.tgz
-rwx------    1 root     root         77296 Oct  7 22:50 bcm_mpi3.v00
-rwx------    1 root     root         29560 Oct  7 22:50 bmcal.v00
-rwx------    1 root     root        283880 Oct  7 22:50 bnxtnet.v00
-rwx------    1 root     root        116358 Oct  7 22:50 bnxtroce.v00
-rwx------    1 root     root          1653 Oct  7 23:00 boot.cfg
-rwx------    1 root     root        601512 Oct  7 22:50 brcmfcoe.v00
-rwx------    1 root     root       1152886 Oct  7 22:50 btldr.v00
-rwx------    1 root     root      13234562 Oct  7 22:50 clusters.v00
-rwx------    1 root     root         45483 Oct  7 22:50 cndi_igc.v00
-rwx------    1 root     root      17965539 Oct  7 22:50 crx.v00
-rwx------    1 root     root      38811319 Oct  7 22:50 drivervm.v00
-rwx------    1 root     root         16592 Oct  7 22:50 dwi2c.v00
-rwx------    1 root     root        459850 Oct  7 22:50 elx_esx_.v00
-rwx------    1 root     root        156772 Oct  7 22:50 elxiscsi.v00
-rwx------    1 root     root        178652 Oct  7 22:50 elxnet.v00
-rwx------    1 root     root        117037 Oct  7 22:50 esx_dvfi.v00
-rwx------    1 root     root       4617966 Oct  7 22:50 esx_ui.v00
-rwx------    1 root     root        193202 Oct  7 22:50 esxio_co.v00
-rwx------    1 root     root        570091 Oct  7 22:50 esxupdt.v00
-rwx------    1 root     root            20 Oct  7 22:50 features.gz
-rwx------    1 root     root         16196 Oct  7 22:50 gc.v00
-rwx------    1 root     root        256855 Oct  7 22:50 i40en.v00
-rwx------    1 root     root        219040 Oct  7 22:50 iavmd.v00
-rwx------    1 root     root        552588 Oct  7 22:50 icen.v00
-rwx------    1 root     root         99502 Oct  7 22:50 igbn.v00
-rwx------    1 root     root        282098 Oct  7 22:50 imgdb.tgz
-rwx------    1 root     root        136172 Oct  7 22:50 ionic_en.v00
-rwx------    1 root     root        205542 Oct  7 22:50 irdman.v00
-rwx------    1 root     root         79994 Oct  7 22:50 iser.v00
-rwx------    1 root     root        164775 Oct  7 22:50 ixgben.v00
-rwx------    1 root     root           116 Oct 12 20:38 jumpstrt.gz
-rwx------    1 root     root       6147526 Oct  7 22:50 k.b00
-rwx------    1 root     root       1165269 Oct  7 22:50 loadesx.v00
-rwx------    1 root     root        855096 Oct  7 22:50 lpfc.v00
-rwx------    1 root     root        177960 Oct  7 22:50 lpnic.v00
-rwx------    1 root     root        101065 Oct  7 22:50 lsi_mr3.v00
-rwx------    1 root     root        136892 Oct  7 22:50 lsi_msgp.v00
-rwx------    1 root     root        188365 Oct  7 22:50 lsi_msgp.v01
-rwx------    1 root     root        148821 Oct  7 22:50 lsi_msgp.v02
-rwx------    1 root     root         24679 Oct  7 22:50 lsuv2_hp.v00
-rwx------    1 root     root         25359 Oct  7 22:50 lsuv2_in.v00
-rwx------    1 root     root        436497 Oct  7 22:50 lsuv2_ls.v00
-rwx------    1 root     root          2790 Oct  7 22:50 lsuv2_nv.v00
-rwx------    1 root     root          4414 Oct  7 22:50 lsuv2_oe.v00
-rwx------    1 root     root          4166 Oct  7 22:50 lsuv2_oe.v01
-rwx------    1 root     root         22170 Oct  7 22:50 lsuv2_sm.v00
-rwx------    1 root     root         72228 Oct  7 22:50 mtip32xx.v00
-rwx------    1 root     root        616746 Oct  7 22:50 native_m.v00
-rwx------    1 root     root        178932 Oct  7 22:50 ne1000.v00
-rwx------    1 root     root         78028 Oct  7 22:50 nenic.v00
-rwx------    1 root     root        219720 Oct  7 22:50 nfnic.v00
-rwx------    1 root     root        189734 Oct  7 22:50 nhpsa.v00
-rwx------    1 root     root        978896 Oct  7 22:50 nmlx5_co.v00
-rwx------    1 root     root        112363 Oct  7 22:50 nmlx5_rd.v00
-rwx------    1 root     root         35727 Oct  7 22:50 ntg3.v00
-rwx------    1 root     root         39891 Oct  7 22:50 nvme_pci.v00
-rwx------    1 root     root         48768 Oct  7 22:50 nvmerdma.v00
-rwx------    1 root     root         61620 Oct  7 22:50 nvmetcp.v00
-rwx------    1 root     root         58526 Oct  7 22:50 nvmxnet3.v00
-rwx------    1 root     root         49435 Oct  7 22:50 nvmxnet3.v01
-rwx------    1 root     root         82685 Oct  7 22:53 preupgrade-state.tgz
-rwx------    1 root     root          9093 Oct  7 22:50 procfs.b00
-rwx------    1 root     root         30032 Oct  7 22:50 pvscsi.v00
-rwx------    1 root     root         89887 Oct  7 22:50 qcnic.v00
-rwx------    1 root     root       1423118 Oct  7 22:50 qedentv.v00
-rwx------    1 root     root       1222739 Oct  7 22:50 qedrntv.v00
-rwx------    1 root     root        947175 Oct  7 22:50 qfle3.v00
-rwx------    1 root     root        344824 Oct  7 22:50 qfle3f.v00
-rwx------    1 root     root        110021 Oct  7 22:50 qfle3i.v00
-rwx------    1 root     root        202099 Oct  7 22:50 qflge.v00
-rwx------    1 root     root        814572 Oct  7 22:50 qlnative.v00
-rwx------    1 root     root        165062 Oct  7 22:50 rdmahl.v00
-rwx------    1 root     root        218365 Oct  7 22:50 rste.v00
-rwx------    1 root     root      25005242 Oct  7 22:50 s.v00
-rwx------    1 root     root      54617368 Oct  7 22:50 sb.v00
-rwx------    1 root     root        246317 Oct  7 22:50 sfvmk.v00
-rwx------    1 root     root        176925 Oct  7 22:50 smartpqi.v00
-rwx------    1 root     root        226072 Oct 12 20:44 state.tgz
-rwx------    1 root     root          9193 Oct  7 22:50 tpm.v00
-rwx------    1 root     root          3588 Oct  7 22:50 tpmesxup.v00
-rwx------    1 root     root      10501494 Oct  7 22:50 trx.v00
-rwx------    1 root     root         15291 Oct  7 22:50 uc_amd.b00
-rwx------    1 root     root            29 Oct  7 22:50 uc_hygon.b00
-rwx------    1 root     root       1941978 Oct  7 22:50 uc_intel.b00
-rwx------    1 root     root          4123 Oct  7 23:00 unlocker.tgz
-rwx------    1 root     root            42 Oct  7 22:50 useropts.gz
-rwx------    1 root     root       5216970 Oct  7 22:50 vdfs.v00
-rwx------    1 root     root      31443474 Oct  7 22:50 vim.v00
-rwx------    1 root     root         57793 Oct  7 22:50 vmkata.v00
-rwx------    1 root     root         91142 Oct  7 22:50 vmksdhci.v00
-rwx------    1 root     root        335607 Oct  7 22:50 vmkusb.v00
-rwx------    1 root     root         66586 Oct  7 22:50 vmw_ahci.v00
-rwx------    1 root     root         55231 Oct  7 22:50 vmware_e.v00
-rwx------    1 root     root      39998726 Oct  7 22:50 vmx.v00
-rwx------    1 root     root      16197164 Oct  7 22:50 vsan.v00
-rwx------    1 root     root        532539 Oct  7 22:50 vsanheal.v00
-rwx------    1 root     root       5524131 Oct  7 22:50 vsanmgmt.v00
-rwx------    1 root     root       1233101 Oct  7 22:50 weaselin.v00
-rwx------    1 root     root       1449882 Oct  7 22:50 xorg.v00
```
[ESXi-macOSFresh.vmx.txt](https://github.com/DrDonk/esxi-unlocker/files/9946967/ESXi-macOSFresh.vmx.txt)
[ESXi-vmware.log.txt](https://github.com/DrDonk/esxi-unlocker/files/9946968/ESXi-vmware.log.txt)
[WRKS-macOSFresh.vmx.txt](https://github.com/DrDonk/esxi-unlocker/files/9946969/WRKS-macOSFresh.vmx.txt)
[WRKS-vmware.log.txt](https://github.com/DrDonk/esxi-unlocker/files/9946970/WRKS-vmware.log.txt)

**Comment by DrDonk** [comment] 2022-11-08 11:48
Thanks for the details.

Firstly you are double unlocking which gives the vmkctl error. You need to remove the old unlocker using SSH or Console:

`BootModuleConfig.sh --remove=unlocker.tgz`

I suggest you run relock at this point to get a clean unpatched system, via a reboot. Then run V 4 unlock again.

(I have fixed the error when trying lt patch vmkctl twice which is in the repo and will be 4.0.4 fix.)

I think this is definitely a case of Apple dropping older Intel CPU support and this also affecting AMD as well. Unfortunetly just hacking the CPUID won't help. As VMware virtualises the CPU the macOS kernel will still issue instructions that may or may not be present. I believe we may be heading to having to use something like OCLP (https://dortania.github.io/OpenCore-Legacy-Patcher/) to make Ventura and future macOS work on older CPUs. There is no patching I can do on VMX files to fix this.

I do not have access to much kit these days having retired from software development, just my son's AMD laptop.

**Comment by DrDonk** [comment] 2022-11-08 13:12
I have posted a page on how to capture macOS debug info https://github.com/DrDonk/unlocker/wiki/Debugging-macOS-Guests

If you have time you could try on Workstation and ESXi and post the files here.

**Comment by ashleyw-gh** [comment] 2022-11-08 21:04
awesome, thanks for that, I can confirm when I followed your instructions, the unlocker correctly patches all components on vsphere8 now - which is great - my old Catalina VM continues to boot correctly which is great.
The same issue as before occurs with my Ventura VM - I'll run those debug traces when I get a chance and update the #47 ticket.
Ideally I'd like to temporarily install windows 11 on my ESXi server natively to see if I can reproduce the same issue on Workstation using the same hardware as esxi - to reconfirm this is an AMD only issue.
thanks again.

**Comment by DrDonk** [comment] 2022-11-25 11:19
@ashleyw-gh I'm going to close this now as we have work arounds for ESXi8 on supported CPUs via 7.0 U2 hardware profile. Pity about AMD and pre-Haswell CPUs, but seemed sort of inevitable.

Thanks to everyone for the testing.

**Closed by DrDonk** 2022-11-25 11:19 UTC
